version: '3'
services:
    mysql-development:
      image: mysql:8.2
      container_name: journal-mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: development
        MYSQL_USER: admin
        MYSQL_PASSWORD: Theline@12321
      ports:
        - "3306:3306"
        - "33060:33060"
      working_dir: /var/lib/mysql
      volumes:
        - "./mysql:/var/lib/mysql"
        - "e:/Personal/journal_docker:/var/www/html/"